### ISSUE TITLE
Deploying all `.md` pages with github pages through YAML script

### ISSUE THREAD

**Issue by rohan472000** [rohan472000/GCP-ACE-certification#5]
@cclauss I'm trying to deploy all `.md` pages inside this repo along with README.md, but only README.md file is getting deployed.
Kindly suggest any solution or modification in `jekyll-gh-pages.yml`.

**Comment by cclauss** [comment]
I would first try to get this working on https://rohan472000.github.io by going thru the steps at https://pages.github.com

Once that is debugged, you can try again on a normal GitHub repo.
